os: windows
language: node_js
node_js:
  - node

env:
  global:
    - "GIT_REPO_SLUG=dullage/tahskr"
    - "VERSION_BUMP_MESSAGE_PREFIX='Travis CI: Bump version to'"
# secret:
#   - DEPLOY_HOST_IP
#   - encrypted_7df0bf92a043_iv
#   - encrypted_7df0bf92a043_key
#   - GITHUB_TOKEN
#   - DEPLOY_TARGET_DIR

if: (tag IS blank AND commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)) OR (tag IS present)

install: skip

script:
  - echo Skipping Build...
  # - bash $TRAVIS_BUILD_DIR/.travis/build.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis/bump_version.sh
    on:
      #repo: env(GIT_REPO_SLUG)
      branch: feature/travis-builds
      tags: false
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
    on:
      #repo: env(GIT_REPO_SLUG)
      branch: feature/travis-builds
      tags: true
