os: windows
language: node_js
node_js:
  - node

env:
  global:
    - "GIT_REPO_SLUG=dullage/tahskr"
    - "VERSION_BUMP_MESSAGE_PREFIX='Travis CI: Bump version to'"
# secret:
#   - DEPLOY_HOST_IP
#   - DEPLOY_DIR_DEV
#   - encrypted_7df0bf92a043_iv
#   - encrypted_7df0bf92a043_key
#   - GITHUB_TOKEN

#   - DEPLOY_SCRIPT_DEV
#   - DEPLOY_SCRIPT_PROD

install:
  # - sudo apt update
  # - sudo apt -y install jq
  - npm ci

if: tag IS NOT present

stages:
  # - name: Bump Version
  #   if: branch = master && type = push && commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Test Build
    if: commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)

  # - name: Build & Deploy Prod
  #   if: branch = master && type = push && commit_message =~ env(VERSION_BUMP_MESSAGE_PREFIX)

  # - name: Build & Deploy Dev
  #   if: branch = develop && type = push

jobs:
  include:
    # - stage: Bump Version
    #   script: bash ./.travis/bump_version.sh

    - stage: Test Build
      before_install:
        - choco install openssl.light -y
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/bump_version.sh
        - npm run build
        - npm run package-win
      before_deploy:
        - choco install python
      deploy:
        skip_cleanup: true
        provider: script
        script: bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
        on:
          branch: feature/travis-builds

    # - stage: Build & Deploy Prod
    #   script: bash ./.travis/build.sh prod

    # - stage: Build & Deploy Dev
    #   script: bash ./.travis/build.sh dev
