os: windows
language: node_js
node_js:
  - node

env:
  global:
    - "GIT_REPO_SLUG=dullage/tahskr"
    - "VERSION_BUMP_MESSAGE_PREFIX='Travis CI: Bump version to'"
# secret:
#   - DEPLOY_HOST_IP
#   - encrypted_7df0bf92a043_iv
#   - encrypted_7df0bf92a043_key
#   - GITHUB_TOKEN
#   - DEPLOY_TARGET_DIR

if: (tag IS blank AND commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)) OR (tag IS present)

install: skip

script:
  - echo Skipping Build...
  # - npm ci
  # - npm run build
  # - npm run package-win

#before_deploy: 7z a tahskr.zip $TRAVIS_BUILD_DIR/builds/tahskr-win32-ia32/*
before_deploy: 7z a tahskr.zip $TRAVIS_BUILD_DIR/*

deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis/bump_version.sh
    on:
      repo: Dullage/tahskr
      branch: feature/travis-builds
      tags: false
  # - provider: script
  #   skip_cleanup: true
  #   script: bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
  #   on:
  #     repo: Dullage/tahskr
  #     branch: feature/travis-builds
  #     tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: nlPdsz0m/8jLOZrwB6Mo0XcqTFG+sFGVZxTHu6Kq+lKBtkKY2eAUXOJJBFIGRHi/DBOKFsT3NJyVroJ62ZSCba1UAE5bfsHaJzt7s+cMyi8q/pRzjQ8DMh7j//3cq6fEbahfFjuRg3i7h4Hy0z+c4Hj+8yTmKKX64In23uhmoQTnwM2zxr9sktyVZ+8sYc$
    file: tahskr.zip
    on:
      repo: Dullage/tahskr
      branch: feature/travis-builds
      tags: true
